### ISSUE TITLE
New tagged version please 

### ISSUE THREAD

**Issue by kpalin** [RabadanLab/arcasHLA#59] opened 2021-02-19 12:56 UTC
Hi,

I'm trying out arcasHLA but aparently the version in bioconda doesn't work due to the git lfs update.  Can you please make a new tag:ed release, and update the bioconda recipe.  That would help many people a lot.

Also, updating the HLA database versions would be nice.  Now it only goes to 3.34.0 (or so) while https://github.com/ANHIG/IMGTHLA is at 3.43.0

Thanks

**Comment by tpereachamblee** [comment] 2021-03-17 18:27
Hello! Thanks for your interest in our tool. This is correct, as of right now the supported database versions are 3.34.0 and lower.  As such, the reference script should be run with `--version 3.34.0` as a flag (or any lower version) and, unfortunately, passing `--update` as a flag (which by design always grabs the latest HLA database) fails. 

Moreover, you are also correct that the present tagged release does not work as expected due to the git lfs update, and in the meantime we recommend cloning directly from the master.

We are presently working to resolve the outstanding issues with the codebase and will release a new tagged as soon as possible (I will close this issue once we do). Thank you for your constructive feedback.

**Closed** 2021-04-13 23:57 UTC

**Comment by tpereachamblee** [comment] 2021-12-09 15:17
Hello! Thanks for your interest in our tool. An updated release with up to date IMGT/HLA versions and commit hashes has just been released [(v0.3.0).](https://github.com/RabadanLab/arcasHLA/releases/tag/v0.3.0) Moreover, between major releases users can use the `--commit` flag to manually pass hashes to more recent releases like so:

`arcasHLA reference --commit <IMGT/HLA_commit_hash>`

Additionally, it is worth noting that the `--update` flag always pulls the latest version. Thanks for your constructive feedback.
